export { Navbar } from "./Navbar";
export { Header } from "./Header";
export { ProjectCv } from "./ProjectCv";
export { Demand } from "./Demand";
export { Markets } from "./Markets";
export { Marketing } from "./Marketing";
export { MarketingStrategy } from "./MarketingStrategy";
export { Facilites } from "./Facilites";
export { DemandMarkets } from "./DemandMarkets";
export { Contact } from './Contact'