import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
// import './fonts.css'

const brandFont = localFont({
  src: [
    {
      path: "../public/fonts/brandFont.ttf",
      style: "normal",
    }
  ],
  variable: "--font-brand",
  weight: "600"
})

const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "700"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brandFont.variable} ${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${montserratSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
